# Generated by Django 4.2.7 on 2025-06-08 04:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chatbots', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Nome do Fluxo')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('is_main_flow', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('nodes', models.JSONField(default=list)),
                ('edges', models.JSONField(default=list)),
                ('viewport', models.JSONField(default=dict)),
                ('settings', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chatbot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flows', to='chatbots.chatbot')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Fluxo',
                'verbose_name_plural': 'Fluxos',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='FlowExecution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=255)),
                ('user_data', models.JSONField(default=dict)),
                ('current_node_id', models.CharField(max_length=255, null=True)),
                ('status', models.CharField(choices=[('active', 'Ativo'), ('completed', 'Concluído'), ('abandoned', 'Abandonado'), ('error', 'Erro')], default='active', max_length=20)),
                ('variables', models.JSONField(default=dict)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('flow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='flows.flow')),
            ],
            options={
                'verbose_name': 'Execução de Fluxo',
                'verbose_name_plural': 'Execuções de Fluxos',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='FlowTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('customer_service', 'Atendimento ao Cliente'), ('lead_generation', 'Geração de Leads'), ('survey', 'Pesquisa'), ('faq', 'FAQ'), ('booking', 'Agendamento'), ('ecommerce', 'E-commerce'), ('other', 'Outros')], max_length=50)),
                ('template_nodes', models.JSONField()),
                ('template_edges', models.JSONField()),
                ('template_settings', models.JSONField(default=dict)),
                ('is_public', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('usage_count', models.PositiveIntegerField(default=0)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Template de Fluxo',
                'verbose_name_plural': 'Templates de Fluxos',
                'ordering': ['-usage_count', 'name'],
            },
        ),
        migrations.CreateModel(
            name='FlowMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('node_id', models.CharField(max_length=255)),
                ('message_type', models.CharField(choices=[('bot', 'Bot'), ('user', 'Usuário'), ('system', 'Sistema')], max_length=20)),
                ('content', models.JSONField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='flows.flowexecution')),
            ],
            options={
                'verbose_name': 'Mensagem do Fluxo',
                'verbose_name_plural': 'Mensagens dos Fluxos',
                'ordering': ['sent_at'],
            },
        ),
    ]
