# Generated by Django 4.2.7 on 2025-06-08 04:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('flows', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComponentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=7)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Categoria de Componente',
                'verbose_name_plural': 'Categorias de Componentes',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ComponentTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('component_type', models.CharField(max_length=50)),
                ('icon', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=7)),
                ('default_data', models.JSONField(default=dict)),
                ('default_settings', models.JSONField(default=dict)),
                ('input_handles', models.JSONField(default=list)),
                ('output_handles', models.JSONField(default=list)),
                ('validation_schema', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='components.componentcategory')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Template de Componente',
                'verbose_name_plural': 'Templates de Componentes',
                'ordering': ['category__order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ComponentInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('node_id', models.CharField(max_length=255)),
                ('position', models.JSONField(default=dict)),
                ('data', models.JSONField(default=dict)),
                ('settings', models.JSONField(default=dict)),
                ('variables', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('flow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='flows.flow')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='components.componenttemplate')),
            ],
            options={
                'verbose_name': 'Instância de Componente',
                'verbose_name_plural': 'Instâncias de Componentes',
                'unique_together': {('flow', 'node_id')},
            },
        ),
        migrations.CreateModel(
            name='ComponentVariable',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('variable_type', models.CharField(choices=[('text', 'Texto'), ('number', 'Número'), ('boolean', 'Booleano'), ('date', 'Data'), ('file', 'Arquivo'), ('array', 'Lista'), ('object', 'Objeto')], default='text', max_length=20)),
                ('default_value', models.JSONField(blank=True, null=True)),
                ('is_required', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('flow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variables', to='flows.flow')),
            ],
            options={
                'verbose_name': 'Variável do Componente',
                'verbose_name_plural': 'Variáveis dos Componentes',
                'unique_together': {('flow', 'name')},
            },
        ),
        migrations.CreateModel(
            name='ComponentConnection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_handle', models.CharField(max_length=255)),
                ('target_handle', models.CharField(max_length=255)),
                ('connection_data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('flow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections', to='flows.flow')),
                ('source_component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_connections', to='components.componentinstance')),
                ('target_component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_connections', to='components.componentinstance')),
            ],
            options={
                'verbose_name': 'Conexão de Componente',
                'verbose_name_plural': 'Conexões de Componentes',
                'unique_together': {('source_component', 'target_component', 'source_handle', 'target_handle')},
            },
        ),
    ]
