# Generated by Django 4.2.7 on 2025-06-08 04:03

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('flows', '0001_initial'),
        ('chatbots', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('node_id', models.CharField(max_length=255, null=True)),
                ('message_type', models.CharField(choices=[('bot', 'Bot'), ('user', 'Usuário'), ('system', 'Sistema')], max_length=20)),
                ('content', models.JSONField()),
                ('content_type', models.CharField(choices=[('text', 'Texto'), ('image', 'Imagem'), ('video', 'Vídeo'), ('file', 'Arquivo'), ('choice', 'Escolha'), ('input', 'Entrada'), ('system', 'Sistema')], default='text', max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Mensagem do Chat',
                'verbose_name_plural': 'Mensagens do Chat',
                'ordering': ['sent_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=255)),
                ('user_data', models.JSONField(default=dict)),
                ('current_node_id', models.CharField(max_length=255, null=True)),
                ('status', models.CharField(choices=[('active', 'Ativo'), ('waiting', 'Aguardando'), ('completed', 'Concluído'), ('abandoned', 'Abandonado'), ('error', 'Erro')], default='active', max_length=20)),
                ('variables', models.JSONField(default=dict)),
                ('context', models.JSONField(default=dict)),
                ('message_count', models.PositiveIntegerField(default=0)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('referrer', models.URLField(blank=True)),
                ('chatbot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_sessions', to='chatbots.chatbot')),
                ('flow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_sessions', to='flows.flow')),
            ],
            options={
                'verbose_name': 'Sessão de Chat',
                'verbose_name_plural': 'Sessões de Chat',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=100)),
                ('webhook_url', models.URLField()),
                ('payload', models.JSONField()),
                ('headers', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('sent', 'Enviado'), ('failed', 'Falhou'), ('retrying', 'Tentando Novamente')], default='pending', max_length=20)),
                ('response_status', models.PositiveIntegerField(null=True)),
                ('response_data', models.JSONField(null=True)),
                ('error_message', models.TextField(blank=True)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('max_retries', models.PositiveIntegerField(default=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('next_retry', models.DateTimeField(blank=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhook_events', to='executions.chatsession')),
            ],
            options={
                'verbose_name': 'Evento de Webhook',
                'verbose_name_plural': 'Eventos de Webhook',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserInput',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('input_type', models.CharField(choices=[('text', 'Texto'), ('number', 'Número'), ('email', 'Email'), ('phone', 'Telefone'), ('choice', 'Escolha'), ('file', 'Arquivo'), ('date', 'Data')], max_length=20)),
                ('raw_value', models.TextField()),
                ('processed_value', models.JSONField()),
                ('variable_name', models.CharField(max_length=255, null=True)),
                ('is_valid', models.BooleanField(default=True)),
                ('validation_errors', models.JSONField(default=list)),
                ('collected_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='executions.chatmessage')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_inputs', to='executions.chatsession')),
            ],
            options={
                'verbose_name': 'Entrada do Usuário',
                'verbose_name_plural': 'Entradas dos Usuários',
                'ordering': ['collected_at'],
            },
        ),
        migrations.CreateModel(
            name='ExecutionLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('node_id', models.CharField(max_length=255)),
                ('component_type', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('started', 'Iniciado'), ('completed', 'Concluído'), ('failed', 'Falhou'), ('skipped', 'Pulado')], max_length=20)),
                ('input_data', models.JSONField(default=dict)),
                ('output_data', models.JSONField(default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('execution_time', models.FloatField(null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='execution_logs', to='executions.chatsession')),
            ],
            options={
                'verbose_name': 'Log de Execução',
                'verbose_name_plural': 'Logs de Execução',
                'ordering': ['started_at'],
            },
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='executions.chatsession'),
        ),
    ]
